- name: run minions
  shell: docker run -d --restart always --name minions --network host -v /var/run/docker/plugins/:/var/run/docker/plugins --privileged --env ETCD_ENDPOINTS={{ etcd_endpoints }} projecteru2/minions /usr/bin/eru-minions
  register: res
  failed_when: res.rc != 0 and 'Conflict' not in res.stderr

- name: create network
  shell: docker network create --driver calico --ipam-driver calico-ipam --subnet {{ calico_ippool_cidr }} {{ calico_ippool_name }}
  register: res
  failed_when: res.rc != 0 and 'already exists' not in res.stderr
